[project]
name = "py-obsidianmd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-frontmatter>=1.3.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "icecream>=2.2.0",
    "pytest>=9.1.1",
]

[tool.pyright]
ignore = ["test"]